name: shop_app
description: A new Flutter project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.22.0 
  connectivity: ^3.0.6
  
  country_code_picker: ^2.0.2
  future_progress_dialog: ^0.2.0

  shared_preferences: ^2.0.7
  pinput: ^1.2.0
  flutter_login_facebook: ^1.0.1
  http: ^0.13.3
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1
  pay: ^1.0.5

  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/
 